[build]
  base = "frontend/eaduck-frontend"
  command = "cd frontend/eaduck-frontend && npm install && npm run build"
  publish = "frontend/eaduck-frontend/dist/eaduck-frontend/browser"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime" 