CREATE TABLE users (
                       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT users_pkey PRIMARY KEY (id),
                       CONSTRAINT valid_role CHECK (role IN ('STUDENT', 'TEACHER', 'ADMIN')),
                       CONSTRAINT admin_active CHECK (role != 'ADMIN' OR is_active = true)
    );

CREATE TABLE grades (
                        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        student_id int8,
                        subject VARCHAR(100) NOT NULL,
                        grade DECIMAL(4,2) NOT NULL,
                        recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT grades_pkey PRIMARY KEY (id)
);

ALTER TABLE grades
    ADD CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id);