ALTER TABLE users ADD COLUMN nome_completo VARCHAR(255);
ALTER TABLE users ADD COLUMN cpf VARCHAR(14);
ALTER TABLE users ADD COLUMN data_nascimento VARCHAR(10);
ALTER TABLE users ADD COLUMN nome_mae VARCHAR(255);
ALTER TABLE users ADD COLUMN nome_pai VARCHAR(255);
ALTER TABLE users ADD COLUMN telefone VARCHAR(20);
ALTER TABLE users ADD COLUMN endereco VARCHAR(500);

