CREATE TABLE attendances (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    classroom_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    arrival_time TIME,
    observations TEXT,
    discipline VARCHAR(255),
    period VARCHAR(20),
    teacher_id BIGINT,
    CONSTRAINT attendances_pkey PRIMARY KEY (id),
    CONSTRAINT fk_attendances_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendances_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendances_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT unique_attendance UNIQUE (classroom_id, student_id, date),
    CONSTRAINT valid_status CHECK (status IN ('PRESENT', 'ABSENT', 'LATE')),
    CONSTRAINT valid_period CHECK (period IS NULL OR period IN ('MANHA', 'TARDE', 'INTEGRAL'))
);

CREATE INDEX idx_attendances_classroom_date ON attendances(classroom_id, date);
CREATE INDEX idx_attendances_student ON attendances(student_id);
CREATE INDEX idx_attendances_date ON attendances(date);

