-- V2__ADD_NOTIFICATIONS.sql
CREATE TABLE notifications (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int8,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);