CREATE TABLE notifications (
                               id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               user_id int8 REFERENCES users(id),
                               message TEXT NOT NULL,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT notifications_pkey PRIMARY KEY (id)
);