[build]
  base = "frontend/eaduck-frontend"
  command = "npm run build"
  publish = "dist/eaduck-frontend/browser"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime" 